### ISSUE TITLE
KeyError attempting to pull from remote repo

### ISSUE THREAD

**Issue by r0t3n** [dulwich/dulwich#226]
Initial git clone at cli, then edit the contents of a file within the repo using github's web interface, then run 'python2.7 client.py' to update the repo, which throws out the following KeyErrors. Using pyenv with 2.7.3 on vyos/debian.

Fetching using dulwich 0.9.7:

Counting objects: 10, done.
Compressing objects: 100% (7/7), done.
Total 10 (delta 3), reused 0 (delta 0)
Traceback (most recent call last):
  File "./fetch.py", line 18, in <module>
    progress=sys.stdout.write)
  File "/home/vyos/.pyenv/versions/2.7.3/lib/python2.7/site-packages/dulwich/client.py", line 215, in fetch
    commit()
  File "/home/vyos/.pyenv/versions/2.7.3/lib/python2.7/site-packages/dulwich/object_store.py", line 652, in commit
    return self.move_in_pack(path)
  File "/home/vyos/.pyenv/versions/2.7.3/lib/python2.7/site-packages/dulwich/object_store.py", line 624, in move_in_pack
    entries = p.sorted_entries()
  File "/home/vyos/.pyenv/versions/2.7.3/lib/python2.7/site-packages/dulwich/pack.py", line 1119, in sorted_entries
    ret = list(self.iterentries(progress=progress))
  File "/home/vyos/.pyenv/versions/2.7.3/lib/python2.7/site-packages/dulwich/pack.py", line 1107, in iterentries
    for i, result in enumerate(indexer):
  File "/home/vyos/.pyenv/versions/2.7.3/lib/python2.7/site-packages/dulwich/pack.py", line 1256, in _walk_all_chains
    for result in self._walk_ref_chains():
  File "/home/vyos/.pyenv/versions/2.7.3/lib/python2.7/site-packages/dulwich/pack.py", line 1266, in _walk_ref_chains
    self._ensure_no_pending()
  File "/home/vyos/.pyenv/versions/2.7.3/lib/python2.7/site-packages/dulwich/pack.py", line 1262, in _ensure_no_pending
    raise KeyError([sha_to_hex(s) for s in self._pending_ref])
KeyError: ['90126188de10375a078a9995a6872a640bf1fddb']

Fetching using Gittle 0.4.0 + dulwich 0.9.7:

Traceback (most recent call last):
  File "./client.py", line 19, in <module>
    git.pull()
  File "/home/vyos/.pyenv/versions/2.7.3/lib/python2.7/site-packages/gittle/gittle.py", line 360, in pull
    return self.pull_from(origin_uri, branch_name)
  File "/home/vyos/.pyenv/versions/2.7.3/lib/python2.7/site-packages/gittle/gittle.py", line 356, in pull_from
    return self.fetch(origin_uri)
  File "/home/vyos/.pyenv/versions/2.7.3/lib/python2.7/site-packages/gittle/gittle.py", line 407, in fetch
    remote_refs = self.fetch_remote(origin_uri)
  File "/home/vyos/.pyenv/versions/2.7.3/lib/python2.7/site-packages/gittle/gittle.py", line 367, in fetch_remote
    remote_refs = client.fetch(remote_path, self.repo)
  File "/home/vyos/.pyenv/versions/2.7.3/lib/python2.7/site-packages/dulwich/client.py", line 215, in fetch
    commit()
  File "/home/vyos/.pyenv/versions/2.7.3/lib/python2.7/site-packages/dulwich/object_store.py", line 652, in commit
    return self.move_in_pack(path)
  File "/home/vyos/.pyenv/versions/2.7.3/lib/python2.7/site-packages/dulwich/object_store.py", line 624, in move_in_pack
    entries = p.sorted_entries()
  File "/home/vyos/.pyenv/versions/2.7.3/lib/python2.7/site-packages/dulwich/pack.py", line 1119, in sorted_entries
    ret = list(self.iterentries(progress=progress))
  File "/home/vyos/.pyenv/versions/2.7.3/lib/python2.7/site-packages/dulwich/pack.py", line 1107, in iterentries
    for i, result in enumerate(indexer):
  File "/home/vyos/.pyenv/versions/2.7.3/lib/python2.7/site-packages/dulwich/pack.py", line 1256, in _walk_all_chains
    for result in self._walk_ref_chains():
  File "/home/vyos/.pyenv/versions/2.7.3/lib/python2.7/site-packages/dulwich/pack.py", line 1266, in _walk_ref_chains
    self._ensure_no_pending()
  File "/home/vyos/.pyenv/versions/2.7.3/lib/python2.7/site-packages/dulwich/pack.py", line 1262, in _ensure_no_pending
    raise KeyError([sha_to_hex(s) for s in self._pending_ref])
KeyError: ['2e802a22e70f936156712ca5c8d56838866405ce']

**Comment by crbunney** [comment]
I'm encountering this issue as well. I'm afraid I don't have complete steps to reproduce or a test repo, but I've found that passing `thin_packs=False` to `get_transport_and_path` stops it happening.

I'm creating my client using this line:
```python
client, path = get_transport_and_path(remote_url)  # add thin_packs=False to make KeyError go away
```
The remote URL is of the form `git@github.com:myorg/private.git`

My environment:
* python: 2.7.6
* dulwich: 0.11.2

Hope that helps,

Full Traceback:
```python
Traceback (most recent call last):
  File "/apps/devutils/src/delivery/packaging/packaging/core.py", line 232, in _pull_branch
    remote_refs = client.fetch(path, self.repo)
  File "/Users/chrisbunney/.virtualenvs/packaging/lib/python2.7/site-packages/dulwich/client.py", line 247, in fetch
    commit()
  File "/Users/chrisbunney/.virtualenvs/packaging/lib/python2.7/site-packages/dulwich/object_store.py", line 639, in commit
    return self.move_in_pack(path)
  File "/Users/chrisbunney/.virtualenvs/packaging/lib/python2.7/site-packages/dulwich/object_store.py", line 617, in move_in_pack
    entries = p.sorted_entries()
  File "/Users/chrisbunney/.virtualenvs/packaging/lib/python2.7/site-packages/dulwich/pack.py", line 1159, in sorted_entries
    ret = list(self.iterentries(progress=progress))
  File "/Users/chrisbunney/.virtualenvs/packaging/lib/python2.7/site-packages/dulwich/pack.py", line 1147, in iterentries
    for i, result in enumerate(indexer):
  File "/Users/chrisbunney/.virtualenvs/packaging/lib/python2.7/site-packages/dulwich/pack.py", line 1288, in _walk_all_chains
    for result in self._walk_ref_chains():
  File "/Users/chrisbunney/.virtualenvs/packaging/lib/python2.7/site-packages/dulwich/pack.py", line 1298, in _walk_ref_chains
    self._ensure_no_pending()
  File "/Users/chrisbunney/.virtualenvs/packaging/lib/python2.7/site-packages/dulwich/pack.py", line 1294, in _ensure_no_pending
    raise KeyError([sha_to_hex(s) for s in self._pending_ref])
KeyError: ['955768b82e64ad20ade1b6fa0c4ccc3db127aef5']
```

**Comment by jelmer** [comment]
Can you still reproduce this?

**Comment by jelmer** [comment]
I'm going to optimistically clone this - I haven't been able to reproduce this myself in a long time.
