### ISSUE TITLE
move_in_pack() can fail on Windows if the target already exists

### ISSUE THREAD

**Issue by earlchew** [dulwich/dulwich#559]
```
======================================================================
ERROR: test_repack_existing (dulwich.tests.test_object_store.DiskObjectStoreTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\projects\dulwich\dulwich\tests\test_object_store.py", line 311, in test_repack_existing
    self.assertEqual(2, self.store.repack())
  File "c:\projects\dulwich\dulwich\object_store.py", line 367, in repack
    consolidated = self.add_objects(objects)
  File "c:\projects\dulwich\dulwich\object_store.py", line 441, in add_objects
    return commit()
  File "c:\projects\dulwich\dulwich\object_store.py", line 701, in commit
    return self.move_in_pack(path)
  File "c:\projects\dulwich\dulwich\object_store.py", line 681, in move_in_pack
    os.rename(path, basename + ".pack")
WindowsError: [Error 183] Cannot create a file when that file already exists
```

**Comment by earlchew** [comment]
This is a known issue: https://stackoverflow.com/questions/8107352

**Comment by jelmer** [comment]
There's a workaround in dulwich.file._fancy_rename to work around this.

One option would be to just avoid writing the file if it already exists - it's supposed to have the same contents as the new file.
