### ISSUE TITLE
porcelain web_daemon unclear how to use

### ISSUE THREAD

**Issue by dominiquevocat** [dulwich/dulwich#610]
What is the way to successfully run a web_daemon unsing porcelain?

I run into the issue, that dulwich\server.py fails in open_repository after joining path and root folder since the relative web url always starts with a / resulting in os.path.join to skip the basepath since the relative path is from root :-( resulting in 
NotGitRepository: Path '/' not inside root 'h:\\etc\\apps\\test\\' (on a windows box, same on linux)

is it me or do i miss something?

i have a folder structure like /opt/something/etc/apps/ with folders in it that have or have not a .git (repo) and would like to serve this - can i just set /opt/something/etc/apps/ as root and then access the repos using http://>servername>:8123/<foldername> or how would this work?

**Comment by jelmer** [comment]
How are you invoking the web_daemon() function exactly?

If you're looking for a web viewer, you'd want to look at something like klaus (https://github.com/jonashaag/klaus). porcelain.web_daemon() will just allow you to clone the repository with git.

**Comment by dominiquevocat** [comment]
hi,

on the server side i run this

```
import os
import sys
from getopt import getopt
import optparse
import signal
from dulwich import log_utils
import logging

logging.getLogger("git").debug
logging.basicConfig(level=logging.DEBUG, stream=sys.stderr,
                        format='%(asctime)s %(levelname)s: %(message)s')

args = sys.argv

parser = optparse.OptionParser()
parser.add_option("-l", "--listen_address", dest="listen_address",
                          default="",
                          help="Binding IP address.")
parser.add_option("-p", "--port", dest="port", type=int,
                          default=8123,
                          help="Binding TCP port.")
options, args = parser.parse_args(args)

log_utils.default_logging_config()
print args
if len(args) > 1:
    gitdir = args[1]
else:
    gitdir = ".." #repoPath
from dulwich import porcelain

#show last log entry from repo to test if repo is readable etc - will fail if it is not directly a repo
#porcelain.log(gitdir, max_entries=1)
#print os.getcwd()
#os.chdir(gitdir)

porcelain.web_daemon(gitdir, address=options.listen_address,
                             port=options.port)
```

running it in a folder that is a repo and passing . as gitdir
and then running on the client side i try to do git ls-remote
with this in .git/config

```
[remote "origin"]
        url = http://localhost:8123/
        fetch = +refs/heads/*:refs/remotes/origin/*
```

on the serverside this gives me the output (with a little debug output extra)

```
/opt/splunk/git> /opt/splunk/bin/splunk cmd python miniserver.py .
['miniserver.py', '.']
2018-01-24 16:53:00,582 DEBUG: init root .
2018-01-24 16:53:00,583 DEBUG: init root /opt/splunk/git
2018-01-24 16:53:18,412 DEBUG: opening repository at /
2018-01-24 16:53:18,412 DEBUG: self root /opt/splunk/git/
2018-01-24 16:53:18,412 DEBUG: joined path /
2018-01-24 16:53:18,412 DEBUG: absolute path //
2018-01-24 16:53:18,413 INFO: "GET /info/refs?service=git-upload-pack HTTP/1.1" 200 0
2018-01-24 16:53:18,413 ERROR: Exception happened during processing of request
Traceback (most recent call last):
  File "/opt/splunk/lib/python2.7/wsgiref/handlers.py", line 86, in run
    self.finish_response()
  File "/opt/splunk/lib/python2.7/wsgiref/handlers.py", line 127, in finish_response
    for data in self.result:
  File "/opt/splunk/git/dulwich/web.py", line 186, in get_info_refs
    http_req=req, advertise_refs=True)
  File "/opt/splunk/git/dulwich/server.py", line 289, in __init__
    self.repo = backend.open_repository(args[0])
  File "/opt/splunk/git/dulwich/server.py", line 213, in open_repository
    (path, self.root))
NotGitRepository: Path '/' not inside root '/opt/splunk/git/'
2018-01-24 16:53:18,416 INFO: "GET /info/refs?service=git-upload-pack HTTP/1.1" 500 59
2018-01-24 16:53:18,416 ERROR: Exception happened during processing of request from ('127.0.0.1', 38406)
Traceback (most recent call last):
  File "/opt/splunk/lib/python2.7/SocketServer.py", line 290, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/opt/splunk/lib/python2.7/SocketServer.py", line 318, in process_request
    self.finish_request(request, client_address)
  File "/opt/splunk/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/opt/splunk/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/opt/splunk/git/dulwich/web.py", line 469, in handle
    handler.run(self.server.get_app())
  File "/opt/splunk/lib/python2.7/wsgiref/handlers.py", line 92, in run
    self.close()
  File "/opt/splunk/lib/python2.7/wsgiref/simple_server.py", line 33, in close
    self.status.split(' ',1)[0], self.bytes_sent
AttributeError: 'NoneType' object has no attribute 'split'
```

the client says
```
git ls-remote
fatal: unable to access 'http://localhost:8123/': Empty reply from server
```

does that help?

**Comment by dominiquevocat** [comment]
in the end i would like to provide the three urls /refs/heads (?) upload and download pack behind a rest service (splunk) but first i want to see if it works kinda and if that is all right proceed.

**Comment by jelmer** [comment]
You're specifying a different path than you're actually exporting. You'd want:

git clone http://localhost:8123/opt/splunk/git

To get different behaviour, you can look at providing your own version of dulwich.server.FilesystemBackend in combination with dulwich.web.make_server.
