### ISSUE TITLE
TypeError: genpack() got an unexpected keyword argument 'ofs_delta' when pushing to EMPTY git repository with 0.19.x

### ISSUE THREAD

**Issue by romke** [dulwich/dulwich#622]
When using hggit and pushing to EMPTY git repository (on bitbucket), I got:
TypeError: genpack() got an unexpected keyword argument 'ofs_delta'

```
pip freeze -l
certifi==2018.4.16
dulwich==0.19.2
hg-git==0.8.11
mercurial==4.5.3
urllib3==1.22
```

on `dulwich==0.18.6` everything goes smoothly

Trace below:
```
** unknown exception encountered, please report by visiting
** https://mercurial-scm.org/wiki/BugTracker
** Python 2.7.10 (default, May 16 2016, 10:18:36) [GCC 4.9.3]
** Mercurial Distributed SCM (version 4.5.3)
** Extensions loaded: transplant, convert, strip, mq, graphlog, pager, hggit
Traceback (most recent call last):
  File "/home/romke/tmp/hggit/bin/hg", line 41, in <module>
    dispatch.run()
  File "/home/romke/tmp/hggit/lib/python2.7/site-packages/mercurial/dispatch.py", line 88, in run
    status = (dispatch(req) or 0) & 255
  File "/home/romke/tmp/hggit/lib/python2.7/site-packages/mercurial/dispatch.py", line 183, in dispatch
    ret = _runcatch(req)
  File "/home/romke/tmp/hggit/lib/python2.7/site-packages/mercurial/dispatch.py", line 324, in _runcatch
    return _callcatch(ui, _runcatchfunc)
  File "/home/romke/tmp/hggit/lib/python2.7/site-packages/mercurial/dispatch.py", line 332, in _callcatch
    return scmutil.callcatch(ui, func)
  File "/home/romke/tmp/hggit/lib/python2.7/site-packages/mercurial/scmutil.py", line 154, in callcatch
    return func()
  File "/home/romke/tmp/hggit/lib/python2.7/site-packages/mercurial/dispatch.py", line 314, in _runcatchfunc
    return _dispatch(req)
  File "/home/romke/tmp/hggit/lib/python2.7/site-packages/mercurial/dispatch.py", line 918, in _dispatch
    cmdpats, cmdoptions)
  File "/home/romke/tmp/hggit/lib/python2.7/site-packages/mercurial/dispatch.py", line 673, in runcommand
    ret = _runcommand(ui, options, cmd, d)
  File "/home/romke/tmp/hggit/lib/python2.7/site-packages/hgext/pager.py", line 77, in pagecmd
    return orig(ui, options, cmd, cmdfunc)
  File "/home/romke/tmp/hggit/lib/python2.7/site-packages/mercurial/dispatch.py", line 926, in _runcommand
    return cmdfunc()
  File "/home/romke/tmp/hggit/lib/python2.7/site-packages/mercurial/dispatch.py", line 915, in <lambda>
    d = lambda: util.checksignature(func)(ui, *args, **strcmdopt)
  File "/home/romke/tmp/hggit/lib/python2.7/site-packages/mercurial/util.py", line 1195, in check
    return func(*args, **kwargs)
  File "/home/romke/tmp/hggit/lib/python2.7/site-packages/mercurial/util.py", line 1195, in check
    return func(*args, **kwargs)
  File "/home/romke/tmp/hggit/lib/python2.7/site-packages/hgext/mq.py", line 3583, in mqcommand
    return orig(ui, repo, *args, **kwargs)
  File "/home/romke/tmp/hggit/lib/python2.7/site-packages/mercurial/util.py", line 1195, in check
    return func(*args, **kwargs)
  File "/home/romke/tmp/hggit/lib/python2.7/site-packages/mercurial/commands.py", line 4194, in push
    opargs=opargs)
  File "/home/romke/tmp/hggit/lib/python2.7/site-packages/hggit/util.py", line 56, in inner
    return f(*args, **kwargs)
  File "/home/romke/tmp/hggit/lib/python2.7/site-packages/hggit/__init__.py", line 384, in exchangepush
    pushop.cgresult = repo.githandler.push(remote.path, revs, force)
  File "/home/romke/tmp/hggit/lib/python2.7/site-packages/hggit/git_handler.py", line 404, in push
    old_refs, new_refs = self.upload_pack(remote, revs, force)
  File "/home/romke/tmp/hggit/lib/python2.7/site-packages/hggit/git_handler.py", line 1113, in upload_pack
    progress=callback)
  File "/home/romke/tmp/hggit/lib/python2.7/site-packages/dulwich/client.py", line 704, in send_pack
    ofs_delta=(CAPABILITY_OFS_DELTA in negotiated_capabilities))
TypeError: genpack() got an unexpected keyword argument 'ofs_delta'
```

**Comment by jelmer** [comment]
The Dulwich API has changed in 0.19. hg-git needs to be updated to use the new API.

On 17 April 2018 12:42:23 GMT+01:00, romke <notifications@github.com> wrote:
>When using hggit and pushing to EMPTY git repository (on bitbucket), I
>got:
>TypeError: genpack() got an unexpected keyword argument 'ofs_delta'
>
>```
>pip freeze -l
>certifi==2018.4.16
>dulwich==0.19.2
>hg-git==0.8.11
>mercurial==4.5.3
>urllib3==1.22
>```
>
>
>on `dulwich==0.18.6` everything goes smoothly
>
>Trace below:
>```
>** unknown exception encountered, please report by visiting
>** https://mercurial-scm.org/wiki/BugTracker
>** Python 2.7.10 (default, May 16 2016, 10:18:36) [GCC 4.9.3]
>** Mercurial Distributed SCM (version 4.5.3)
>** Extensions loaded: transplant, convert, strip, mq, graphlog, pager,
>hggit
>Traceback (most recent call last):
>  File "/home/romke/tmp/hggit/bin/hg", line 41, in <module>
>    dispatch.run()
>File
>"/home/romke/tmp/hggit/lib/python2.7/site-packages/mercurial/dispatch.py",
>line 88, in run
>    status = (dispatch(req) or 0) & 255
>File
>"/home/romke/tmp/hggit/lib/python2.7/site-packages/mercurial/dispatch.py",
>line 183, in dispatch
>    ret = _runcatch(req)
>File
>"/home/romke/tmp/hggit/lib/python2.7/site-packages/mercurial/dispatch.py",
>line 324, in _runcatch
>    return _callcatch(ui, _runcatchfunc)
>File
>"/home/romke/tmp/hggit/lib/python2.7/site-packages/mercurial/dispatch.py",
>line 332, in _callcatch
>    return scmutil.callcatch(ui, func)
>File
>"/home/romke/tmp/hggit/lib/python2.7/site-packages/mercurial/scmutil.py",
>line 154, in callcatch
>    return func()
>File
>"/home/romke/tmp/hggit/lib/python2.7/site-packages/mercurial/dispatch.py",
>line 314, in _runcatchfunc
>    return _dispatch(req)
>File
>"/home/romke/tmp/hggit/lib/python2.7/site-packages/mercurial/dispatch.py",
>line 918, in _dispatch
>    cmdpats, cmdoptions)
>File
>"/home/romke/tmp/hggit/lib/python2.7/site-packages/mercurial/dispatch.py",
>line 673, in runcommand
>    ret = _runcommand(ui, options, cmd, d)
>File
>"/home/romke/tmp/hggit/lib/python2.7/site-packages/hgext/pager.py",
>line 77, in pagecmd
>    return orig(ui, options, cmd, cmdfunc)
>File
>"/home/romke/tmp/hggit/lib/python2.7/site-packages/mercurial/dispatch.py",
>line 926, in _runcommand
>    return cmdfunc()
>File
>"/home/romke/tmp/hggit/lib/python2.7/site-packages/mercurial/dispatch.py",
>line 915, in <lambda>
>    d = lambda: util.checksignature(func)(ui, *args, **strcmdopt)
>File
>"/home/romke/tmp/hggit/lib/python2.7/site-packages/mercurial/util.py",
>line 1195, in check
>    return func(*args, **kwargs)
>File
>"/home/romke/tmp/hggit/lib/python2.7/site-packages/mercurial/util.py",
>line 1195, in check
>    return func(*args, **kwargs)
>File "/home/romke/tmp/hggit/lib/python2.7/site-packages/hgext/mq.py",
>line 3583, in mqcommand
>    return orig(ui, repo, *args, **kwargs)
>File
>"/home/romke/tmp/hggit/lib/python2.7/site-packages/mercurial/util.py",
>line 1195, in check
>    return func(*args, **kwargs)
>File
>"/home/romke/tmp/hggit/lib/python2.7/site-packages/mercurial/commands.py",
>line 4194, in push
>    opargs=opargs)
>File "/home/romke/tmp/hggit/lib/python2.7/site-packages/hggit/util.py",
>line 56, in inner
>    return f(*args, **kwargs)
>File
>"/home/romke/tmp/hggit/lib/python2.7/site-packages/hggit/__init__.py",
>line 384, in exchangepush
>    pushop.cgresult = repo.githandler.push(remote.path, revs, force)
>File
>"/home/romke/tmp/hggit/lib/python2.7/site-packages/hggit/git_handler.py",
>line 404, in push
>    old_refs, new_refs = self.upload_pack(remote, revs, force)
>File
>"/home/romke/tmp/hggit/lib/python2.7/site-packages/hggit/git_handler.py",
>line 1113, in upload_pack
>    progress=callback)
>File
>"/home/romke/tmp/hggit/lib/python2.7/site-packages/dulwich/client.py",
>line 704, in send_pack
>    ofs_delta=(CAPABILITY_OFS_DELTA in negotiated_capabilities))
>TypeError: genpack() got an unexpected keyword argument 'ofs_delta'
>```
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/dulwich/dulwich/issues/622

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
