### ISSUE TITLE
dulwich.errors.RefFormatError

### ISSUE THREAD

**Issue by DaveInCaz** [dulwich/dulwich#636]
Pushing to a github enterprise server...

** unknown exception encountered, please report by visiting
** https://mercurial-scm.org/wiki/BugTracker
** Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]
** Mercurial Distributed SCM (version 4.5)
** Extensions loaded: convert, graphlog, eol, strip, transplant, rebase, relink, extdiff, hggit, share, shelve
Traceback (most recent call last):
  File "hg", line 61, in <module>
  File "mercurial\dispatch.pyo", line 88, in run
  File "mercurial\dispatch.pyo", line 183, in dispatch
  File "mercurial\dispatch.pyo", line 324, in _runcatch
  File "mercurial\dispatch.pyo", line 332, in _callcatch
  File "mercurial\scmutil.pyo", line 154, in callcatch
  File "mercurial\dispatch.pyo", line 314, in _runcatchfunc
  File "mercurial\dispatch.pyo", line 918, in _dispatch
  File "mercurial\dispatch.pyo", line 673, in runcommand
  File "mercurial\dispatch.pyo", line 926, in _runcommand
  File "mercurial\dispatch.pyo", line 915, in <lambda>
  File "mercurial\util.pyo", line 1195, in check
  File "mercurial\commands.pyo", line 4193, in push
  File "hggit\util.pyo", line 56, in inner
  File "hggit\__init__.pyo", line 384, in exchangepush
  File "hggit\git_handler.pyo", line 403, in push
  File "hggit\git_handler.pyo", line 370, in export_commits
  File "hggit\git_handler.pyo", line 1329, in update_references
  File "dulwich\refs.pyo", line 290, in __setitem__
  File "dulwich\refs.pyo", line 623, in set_if_equals
  File "dulwich\refs.pyo", line 191, in _check_refname
dulwich.errors.RefFormatError: refs/heads/OpenStudio Nuget

**Comment by DaveInCaz** [comment]
Looks like a similar crash here:
https://github.com/schacon/hg-git/issues/324

**Comment by DaveInCaz** [comment]
Another report, from 2012:
https://groups.google.com/forum/#!topic/hg-git/HYVAzDYt3sU

**Comment by DaveInCaz** [comment]
And one more: https://bitbucket.org/durin42/hg-git/issues/163/gexport-fails-on-bookmarks-with-spaces-in

It concludes "Spaces are invalid in Git, refs so Dulwich refuses to create refs with spaces in the name" and also notes "Not only space but russian symbols also".

**Comment by jelmer** [comment]
This is intentional behaviour in Dulwich, spaces are invalid in ref names in git too. See https://git-scm.com/docs/git-check-ref-format

hg-git should probably mangle/strip the spaces before using them in ref names.
