### ISSUE TITLE
Python 3 install broken

### ISSUE THREAD

**Issue by david-caro** [dulwich/dulwich#637]
Hi!

Since the last release, when trying to install dulwich from pip on python3, I'm getting this error:
```
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-d4w9zid2/setup.py", line 128, in <module>
        'Development Status :: 1 - Planning',
      File "/code/.tox/py36/lib/python3.6/site-packages/setuptools/__init__.py", line 128, in setup
        _install_setup_requires(attrs)
      File "/code/.tox/py36/lib/python3.6/site-packages/setuptools/__init__.py", line 123, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/code/.tox/py36/lib/python3.6/site-packages/setuptools/dist.py", line 514, in fetch_build_eggs
        replace_conflicting=True,
      File "/code/.tox/py36/lib/python3.6/site-packages/pkg_resources/__init__.py", line 770, in resolve
        replace_conflicting=replace_conflicting
      File "/code/.tox/py36/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1053, in best_match
        return self.obtain(req, installer)
      File "/code/.tox/py36/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1065, in obtain
        return installer(requirement)
      File "/code/.tox/py36/lib/python3.6/site-packages/setuptools/dist.py", line 581, in fetch_build_egg
        return cmd.easy_install(req)
      File "/code/.tox/py36/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 673, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/code/.tox/py36/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 699, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/code/.tox/py36/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 884, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/code/.tox/py36/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 1149, in build_and_install                                                                                                                  
        self._set_fetcher_options(os.path.dirname(setup_script))
      File "/code/.tox/py36/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 1188, in _set_fetcher_options                                                                                                               
        setopt.edit_config(cfg_filename, settings)
      File "/code/.tox/py36/lib/python3.6/site-packages/setuptools/command/setopt.py", line 43, in edit_config
        opts.read([filename])
      File "/tmp/pip-req-build-d4w9zid2/configparser.py", line 698, in read
        self._read(fp, filename)
      File "/tmp/pip-req-build-d4w9zid2/configparser.py", line 1016, in _read
        for lineno, line in enumerate(fp, start=1):
      File "/code/.tox/py36/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc4 in position 48: ordinal not in range(128)
```

My guess it's that the utf-8 char added to the setup.cfg file is messing up with it.

**Comment by david-caro** [comment]
To reproduce you can run `python setup.py bdist_egg` and `pip install dist/*egg`.

**Comment by david-caro** [comment]
might be a pip issue though

**Comment by david-caro** [comment]
it's strange though.... running `pip install` only seems to fail inside the tox venv...

**Comment by jelmer** [comment]
It works fine here too.

It may dependent on your locale. Do you it set to C or ascii in the venv?

**Comment by david-caro** [comment]
I'm using the python:3.6 container from dockerhub:
```
root@210fd6d5e725:/code# python --version
Python 3.6.5
root@210fd6d5e725:/code# env
PYTHONUNBUFFERED=1
LANG=C.UTF-8
HOSTNAME=210fd6d5e725
GPG_KEY=0D96DF4D4110E5C43FBFB17F2D347EA6AA65421D
PWD=/code
HOME=/root
TERM=xterm
PYTHON_VERSION=3.6.5
SHLVL=1
PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PS1=${debian_chroot:+($debian_chroot)}\u@\h:\w\$ 
TOXENV=py36
PYTHON_PIP_VERSION=10.0.1
_=/usr/bin/env
```

**Comment by david-caro** [comment]
I'm using tox though, so it might mess up with the env.

**Comment by david-caro** [comment]
interesting.... explicitly adding tox as a requirement makes it work, if I let it get pulled as a dependency for another requirement it breaks with the above error, strange.

**Comment by david-caro** [comment]
I correct myself, it fails only if the dependency to dulwich is put in the setup.py file under the `setup_requires`, directly or indirectly.

**Comment by david-caro** [comment]
I think that it's more related to setuptools than pip...

**Comment by david-caro** [comment]
definetly not a dulwich issue, unless you want to work around it until they fix it on pip side.

**Comment by jelmer** [comment]
Can you file a bug about the pip side? I'm happy to put in a workaround and a comment linking to the pip bug.

On 20 June 2018 13:21:43 BST, David Caro <notifications@github.com> wrote:
>definetly not a dulwich issue, unless you want to work around it until
>they fix it on pip side.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/dulwich/dulwich/issues/637#issuecomment-398729468

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by david-caro** [comment]
just opened this in setuptools: https://github.com/pypa/setuptools/issues/1392
I hope it's the right place.

**Comment by jelmer** [comment]
Looks like there was another issue already filed last year:

https://github.com/pypa/setuptools/issues/1062

It has a PR associated but not much happened :(

On 20 June 2018 14:34:30 BST, David Caro <notifications@github.com> wrote:
>just opened this in setuptools:
>https://github.com/pypa/setuptools/issues/1392
>I hope it's the right place.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/dulwich/dulwich/issues/637#issuecomment-398750067

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by jelmer** [comment]
I've removed the unicode digraph for now. We can reintroduce it when setuptools is fixed.
