### ISSUE TITLE
[bug] setup fails

### ISSUE THREAD

**Issue by EgorBu** [dulwich/dulwich#668]
Hello!
Thank you for a great lib!
Unfortunately right now setup fails with this log.
```
Collecting dulwich<1.0,>=0.19 (from modelforge<0.8,>=0.7.0->sourced-ml==0.6.4->-r requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/5d/2a/d2c639a97b5aca864cc1ff834151df0b68fd129f1b95a7068652b777d4cd/dulwich-0.19.7.tar.gz (355kB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-mxmemu0v/dulwich/setup.py", line 87, in <module>
        description = f.read()
      File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc4 in position 2125: ordinal not in range(128)
```

**Comment by der-gabe** [comment]
I'm also seeing this, but only on Python3.

**Comment by jelmer** [comment]
Thanks, merged your fix.
