### ISSUE TITLE
dulwich.tests.test_porcelain.PushTests.test_simple flaps

### ISSUE THREAD

**Issue by jelmer** [dulwich/dulwich#670]
dulwich.tests.test_porcelain.PushTests.test_simple contains a race condition that is hard to hit, but looks something like:

ERROR: test_simple (dulwich.tests.test_porcelain.PushTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/<<PKGBUILDDIR>>/dulwich/tests/test_porcelain.py", line 724, in test_simple
    self.assertEqual(r_clone[b'HEAD'].id, self.repo[refs_path].id)
  File "/<<PKGBUILDDIR>>/dulwich/repo.py", line 528, in __getitem__
    return self.object_store[self.refs[name]]
  File "/<<PKGBUILDDIR>>/dulwich/object_store.py", line 119, in __getitem__
    type_num, uncomp = self.get_raw(sha)
  File "/<<PKGBUILDDIR>>/dulwich/object_store.py", line 461, in get_raw
    raise KeyError(hexsha)
KeyError: b'a031515918b815701865df2363092b8d577d765f'

**Comment by jelmer** [comment]
This has been fixed in 0.19.11.
