### ISSUE TITLE
Error on test_diff_apply with 0.19.12

### ISSUE THREAD

**Issue by polyzen** [dulwich/dulwich#720]
```
======================================================================
ERROR: test_diff_apply (dulwich.tests.test_porcelain.DiffTreeTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-dulwich/src/dulwich-0.19.12/dulwich/tests/test_porcelain.py", line 757, in test_diff_apply
    run_git_or_fail(git_command)
  File "/build/python-dulwich/src/dulwich-0.19.12/dulwich/tests/compat/utils.py", line 145, in run_git_or_fail
    capture_stdout=True, **popen_kwargs)
  File "/build/python-dulwich/src/dulwich-0.19.12/dulwich/tests/compat/utils.py", line 135, in run_git
    p = subprocess.Popen(args, env=env, **popen_kwargs)
  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'git': 'git'

----------------------------------------------------------------------
Ran 1337 tests in 4.117s

FAILED (errors=1, skipped=242)
```
Arch packages installed while building in a container:
`Packages (4) libnsl-1.2.0-1  python-3.7.4-1  python-certifi-2019.6.16-1  python-urllib3-1.25.3-1`
`Packages (8) python-appdirs-1.4.3-2  python-attrs-19.1.0-1  python-packaging-19.1-2  python-pbr-5.4.2-1  python-pyparsing-2.4.2-1  python-setuptools-1:41.0.1-1  python-six-1.12.0-1  python-mock-3.0.5-1`

**Comment by GreenReaper** [comment]
Looks like [this will fix alpha/ppc64/sparc64/x32 builds on Debian ports](https://buildd.debian.org/status/package.php?p=dulwich&suite=sid).

**Comment by jelmer** [comment]
I've uploaded a new version to Debian.
