### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe9 in position 27: ordinal not in range(128)

### ISSUE THREAD

**Issue by timmy61109** [dulwich/dulwich#763]
This is an error that I found. If my file name uses a non-ascii encoding format, the following error will occur. I suggest using `utf8` instead of the following paragraph.

```python
yield '--- {}{}{}'.format(fromfile.decode("utf8"), fromdate, lineterm).encode('utf8')
```

The function that caused the error.

```python
def unified_diff(a, b, fromfile='', tofile='', fromfiledate='', tofiledate='', n=3, lineterm='\n')
```

Error message

```
EEEEEEEEEEE`\xe3\x80\x82\n', ...]
b = [b'Fix Translate FileName SSSSSS~EEEEEE\n', b'\n', b'\xe6\xa8\x99\xe9\xa1\x8c\xe8\xa6\x8f\xe5\x89\x87:\n', b'\n', b'- ...\xab\xe8\xa1\xa8\xe7\xa4\xba\xef\xbc\x8c\xe4\xbe\x8b\xe5\xa6\x82`Fix Translate File SSSSSS~EEEEEE`\xe3\x80\x82\n', ...]
fromfile = b'a/.gitlab/commit_templates/\xe9\x8c\xaf\xe8\xaa\xa4\xe8\xad\xaf\xe6\x96\x87.md', tofile = b'b/.gitlab/commit_templates/\xe9\x8c\xaf\xe8\xaa\xa4\xe8\xad\xaf\xe6\x96\x87.md', fromfiledate = ''
tofiledate = '', n = 3, lineterm = '\n'

    def unified_diff(a, b, fromfile='', tofile='', fromfiledate='',
                     tofiledate='', n=3, lineterm='\n'):
        """difflib.unified_diff that can detect "No newline at end of file" as
        original "git diff" does.
    
        Based on the same function in Python2.7 difflib.py
        """
        started = False
        for group in SequenceMatcher(None, a, b).get_grouped_opcodes(n):
            if not started:
                started = True
                fromdate = '\t{}'.format(fromfiledate) if fromfiledate else ''
                todate = '\t{}'.format(tofiledate) if tofiledate else ''
                yield '--- {}{}{}'.format(
>                   fromfile.decode("ascii"),
                    fromdate,
                    lineterm
                    ).encode('ascii')
E               UnicodeDecodeError: 'ascii' codec can't decode byte 0xe9 in position 27: ordinal not in range(128)

/usr/local/lib/python3.6/dist-packages/dulwich/patch.py:120: UnicodeDecodeError

```

If it is determined that this is the solution, please let it merge, because the company cannot pass the CI check because of this error.

**Comment by timmy61109** [comment]
Hello, since the last improvement, it has been working normally, but now I have encountered the same problem again, which is also a problem with the encoding format, but the error is not the same.

```
檔案 第 6 轮.zh_TW.po 行數 31 

通過驗證時間模板驗證 第 6 轮.zh_TW.po 


Traceback (most recent call last):
  File "manage.py", line 124, in <module>
    diff.po_diff()
  File "/home/timmy/Git/TimeWaver-Translate/translate/analysis_po.py", line 646, in po_diff
    self.commit_diff(commit1=self.master, commit2=self.head)
  File "/home/timmy/Git/TimeWaver-Translate/translate/analysis_po.py", line 665, in commit_diff
    out, repo.object_store, commit1_commit.tree, commit2_commit.tree)
  File "/home/timmy/.local/lib/python3.6/site-packages/dulwich/patch.py", line 305, in write_tree_diff
    (newpath, newmode, newsha), diff_binary=diff_binary)
  File "/home/timmy/.local/lib/python3.6/site-packages/dulwich/patch.py", line 226, in write_object_diff
    patched_old_path, patched_new_path))
  File "/home/timmy/.local/lib/python3.6/site-packages/dulwich/patch.py", line 120, in unified_diff
    fromfile.decode("ascii"),
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 5: ordinal not in range(128)

```

**Comment by timmy61109** [comment]
I found that the GitHub update did not update to PyPi, is this the case?

**Comment by jelmer** [comment]
Yes, pypi only has releases. You'll need to either way for 0.20.3 or check out the version of Dulwich from git.

**Comment by timmy61109** [comment]
Can I help with this issue, will it be automated?

My CIs are all downloaded using PyPi. Although it is okay to download the latest ones using Git and install them using Python, I will find it great if they can be improved or I can help.

**Comment by jelmer** [comment]
On Wed, Jun 10, 2020 at 07:53:54PM -0700, Wu Chenzhi wrote:
> Can I help with this issue, will it be automated?
> 
> My CIs are all downloaded using PyPi. Although it is okay to download the latest ones using Git and install them using Python, I will find it great if they can be improved or I can help.

You can use git+https://github.com/dulwich/dulwich in pip to install straight from git.
