### ISSUE TITLE
Pull on a shallow clone, from a git-daemon-hosted repository, hangs

### ISSUE THREAD

**Issue by mjpieters** [dulwich/dulwich#782]
Using pull on a shallow clone over the `git://` protocol causes the client to hang.

Test setup:

**Git daemon**

```sh
#!/bin/sh
ROOT=$(mktemp -d)
mkdir -p "$ROOT/testrepo"
cd "$ROOT/testrepo"
git init
echo "Monty Python's Flying Circus" > test_file.txt
git add test_file.txt && git commit -m "init"
echo "And now for something completely different" > other_file.txt
git add other_file.txt && git commit -m "addendum"
cd "$ROOT"
git daemon --export-all --verbose --reuseaddr --base-path="$ROOT" "$ROOT"
```

This starts `git daemon` on localhost serving a single repository, `testrepo`, with two commits.

**Dulwich client**

```python
import os
import tempfile
import threading
import sys

from dulwich import porcelain
from dulwich.repo import Repo

remote = "git://localhost/testrepo" if len(sys.argv) < 2 else sys.argv[1]
timeout = 0.5 if len(sys.argv) < 3 else float(sys.argv[2])

def clone_pull(**kwargs):
    with tempfile.TemporaryDirectory() as td:
        repo = porcelain.clone(remote, os.path.join(td, "clientrepo"), checkout=True, **kwargs)
        porcelain.pull(repo, remote)

def test(**kwargs):
    t = threading.Thread(target=clone_pull, kwargs=kwargs, daemon=True)
    t.start()
    t.join(timeout)
    assert not t.is_alive()

test()
test(depth=1)
```

This first clones `testrepo` in full and then pulls, then tries the same thing with `depth=1`. The latter always hangs on any dulwich release I tried (before f1421c85 git daemon would abort the connection with `fatal: Invalid deepen: deepen None`).

**Comment by mjpieters** [comment]
For what it's worth, `python client_daemon_pull.py https://github.com/dulwich/dulwich.git 30` also errors, but for different reasons:

```
Enumerating objects: 37, done.
Counting objects: 100% (37/37), done.
Compressing objects: 100% (29/29), done.
Total 25999 (delta 17), reused 17 (delta 8), pack-reused 25962
Checking out bb62a537d0bc548ac06b7c6d9f919b7741a30802
Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
Enumerating objects: 7984, done.
Counting objects: 100% (7984/7984), done.
Compressing objects: 100% (4172/4172), done.
Total 7984 (delta 5609), reused 5887 (delta 3692), pack-reused 0
Checking out bb62a537d0bc548ac06b7c6d9f919b7741a30802
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/private/tmp/dulwich_bisect/dulwich/dulwich/repo.py", line 556, in get_parents
    return self._graftpoints[sha]
KeyError: b'5924a8f9b061e0cb6bf41bce9c0a9edf8b51a03a'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/.../lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/.../lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "client_daemon_pull.py", line 15, in clone_pull
    porcelain.pull(repo, remote)
  File "/.../dulwich/dulwich/porcelain.py", line 990, in pull
    fetch_result = client.fetch(
  File "/.../dulwich/dulwich/client.py", line 430, in fetch
    result = self.fetch_pack(
  File "/.../dulwich/dulwich/client.py", line 1776, in fetch_pack
    (new_shallow, new_unshallow) = self._handle_upload_pack_head(
  File "/.../dulwich/dulwich/client.py", line 688, in _handle_upload_pack_head
    have = next(graph_walker)
  File "/.../dulwich/dulwich/object_store.py", line 1298, in next
    ps = self.get_parents(ret)
  File "/.../dulwich/dulwich/repo.py", line 559, in get_parents
    commit = self[sha]
  File "/.../dulwich/dulwich/repo.py", line 694, in __getitem__
    return self.object_store[self.refs[name]]
  File "/.../dulwich/dulwich/refs.py", line 299, in __getitem__
    raise KeyError(name)
KeyError: b'5924a8f9b061e0cb6bf41bce9c0a9edf8b51a03a'
```

but that's probably a different issue.

**Comment by jelmer** [comment]
I can reproduce this with 0.20.3, and have verified that it's fixed in master. It appears to be fixed as part of the changes to not request refs that the client already has.
