### ISSUE TITLE
Regression: Can't push to dulwich.server-served repository with no commits

### ISSUE THREAD

**Issue by mjpieters** [dulwich/dulwich#788]
Here is my reproducer script:

```python
import os
import tempfile
import threading

from dulwich import porcelain
from dulwich.repo import Repo
from dulwich.server import DictBackend, TCPGitServer

with tempfile.TemporaryDirectory() as td:
    serverrepo = Repo.init(os.path.join(td, "serverrepo"), mkdir=True)
    # no commits
    backend = DictBackend({b'/': serverrepo})
    dul_server = TCPGitServer(backend, b'localhost', 0)
    try:
        threading.Thread(target=dul_server.serve).start()
        port = dul_server.socket.getsockname()[1]

        remote = f"git://localhost:{port}/"
        repo = porcelain.clone(remote, os.path.join(td, "clientrepo"), checkout=True)
        filepath = os.path.join(repo.path, "testfile.txt")
        with open(filepath, "w") as f:
            f.write("foobar\n")
        porcelain.add(repo, filepath)
        porcelain.commit(repo, b"add a file", committer=b"Foo Barra <fbarra@example.com>")
        porcelain.push(repo, remote, refspecs=[b"master"])
    finally:
        dul_server.shutdown()
```

which fails with:

```python
Traceback (most recent call last):
  File "testscript.py", line 25, in <module>
    porcelain.push(repo, remote, refspecs=[b"master"])
  File "/.../dulwich/porcelain.py", line 980, in push
    result = client.send_pack(
  File "/.../dulwich/client.py", line 843, in send_pack
    new_refs = orig_new_refs = update_refs(dict(old_refs))
  File "/.../dulwich/porcelain.py", line 972, in update_refs
    check_diverged(r, refs[rh], r.refs[lh])
KeyError: b'refs/heads/master'
```

This was working fine in Dulwich 0.20.0.

and if I run `git bisect` with the following `checkcommit.sh` shell script:

```sh
#!/bin/sh
echo 'building extensions'
make clean > /dev/null && make all > /dev/null
echo 'testing client-server interaction'
python testscript.py
```

git tells me this broke with b93c20797b0680bef7aaf16121b74b42efe6b047:

```
$ git bisect log
# bad: [24cafe790aefc5f754e09a306b088c41b64c6280] Use Repo.get_parents, so graft points are considered.
# good: [89bd7162d889b17a5191f9b8b04c16a01241b74f] Release 0.20.0
git bisect start 'master' 'dulwich-0.20.0'
# good: [ef06f58b398456b6e235603d58158c179aa46f34] Update NEWS.
git bisect good ef06f58b398456b6e235603d58158c179aa46f34
# bad: [a049507fb1921500f721b3bf57b0ba8146cc5d85] Check for diverged branches.
git bisect bad a049507fb1921500f721b3bf57b0ba8146cc5d85
# good: [79eafc982850d78721416201ad1d02f6020eef8c] Rename http_req to stateless_req.
git bisect good 79eafc982850d78721416201ad1d02f6020eef8c
# bad: [b93c20797b0680bef7aaf16121b74b42efe6b047] Prepare for a world in which we check for diverged branches.
git bisect bad b93c20797b0680bef7aaf16121b74b42efe6b047
# good: [f401f2f979bc838fc2fa50cbfb3ba61be66f554a] Allow passing in global force argument to parse_reftuple.
git bisect good f401f2f979bc838fc2fa50cbfb3ba61be66f554a
# good: [33e8998f8c21cb195e811c7b951d3d5633f79649] Only fetch objects we don't already have.
git bisect good 33e8998f8c21cb195e811c7b951d3d5633f79649
# first bad commit: [b93c20797b0680bef7aaf16121b74b42efe6b047] Prepare for a world in which we check for diverged branches.
```

I manually tested some of the commits between master and that one and indeed that's the point where pushing to an empty repository broke.

**Comment by mjpieters** [comment]
Now, this may be *intentional*, and `force=True` is required at the moment. with `porcelain.push(repo, remote, refspecs=[b"master"], force=True)` the push succeeds.
