### ISSUE TITLE
Cannot push from shallow fetch

### ISSUE THREAD

**Issue by zakkie** [dulwich/dulwich#794]
## Environment

- OS: linux
- version dulwich==0.20.5
- Python 3.6.9

dulwich==0.20.3 did not reproduce this bug

#### Code

```python
import os

import dulwich
import dulwich.client
import dulwich.porcelain
import paramiko
from dulwich.contrib.paramiko_vendor import _ParamikoWrapper

class ParamikoSSHKeyVendor:
    kw_args = {'key_filename': './id_rsa'}

    @classmethod
    def set_key_file(cls, key_filename):
        cls.kw_args['key_filename'] = key_filename

    def run_command(self, host, command, username='git', port=None):
        if port is None:
            port = 22
        policy = paramiko.client.MissingHostKeyPolicy()
        client = paramiko.SSHClient()
        client.set_missing_host_key_policy(policy)
        client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
        client.connect(host, username=username, port=port, **self.kw_args)

        channel = client.get_transport().open_session()
        channel.exec_command(command)
        return _ParamikoWrapper(client, channel)


def main():
    key_filename = os.path.join(os.getcwd(), 'git_python')
    ParamikoSSHKeyVendor.set_key_file(key_filename)
    dulwich.client.get_ssh_vendor = ParamikoSSHKeyVendor


    remote_repo = 'git@github.com:yamazaki/test.git'
    local_repo = '/tmp/pygit-test'

    repo = dulwich.porcelain.clone(remote_repo, local_repo, depth=1)

    # edit data
    with open(os.path.join(local_repo, 'data'), 'a') as f:
        f.write('hoge\n')

    dulwich.porcelain.add(local_repo, os.path.join(local_repo, 'data'))
    dulwich.porcelain.commit(repo, message=f'updated')
    dulwich.porcelain.push(repo, remote_repo, 'master')

main()
```

#### Console

```
Enumerating objects: 4, done.
Counting objects: 100% (4/4), done.
Compressing objects: 100% (4/4), done.
Total 4 (delta 0), reused 3 (delta 0), pack-reused 0
Checking out bed96c99236a81426c60b23bdd49e1dc59430de9
Traceback (most recent call last):
  File "py-git.py", line 49, in <module>
    main()
  File "py-git.py", line 47, in main
    dulwich.porcelain.push(repo, remote_repo, 'master')
  File "/home/yamazaki/test/venv/lib/python3.6/site-packages/dulwich/porcelain.py", line 984, in push
    progress=errstream.write)
  File "/home/yamazaki/test/venv/lib/python3.6/site-packages/dulwich/client.py", line 843, in send_pack
    new_refs = orig_new_refs = update_refs(dict(old_refs))
  File "/home/yamazaki/test/venv/lib/python3.6/site-packages/dulwich/porcelain.py", line 973, in update_refs
    check_diverged(r.object_store, refs[rh], r.refs[lh])
  File "/home/yamazaki/test/venv/lib/python3.6/site-packages/dulwich/porcelain.py", line 248, in check_diverged
    raise DivergedBranches(current_sha, new_sha)
dulwich.porcelain.DivergedBranches: b'bed96c99236a81426c60b23bdd49e1dc59430de9'
```

**Comment by jelmer** [comment]
Can you try this with master? Parent iteration with shallows should
work there, and I suspect that addresses this.

Jelmer

**Comment by zakkie** [comment]
Same error occurred with master/HEAD.

```
Enumerating objects: 4, done.
Counting objects: 100% (4/4), done.
Compressing objects: 100% (4/4), done.
Total 4 (delta 0), reused 3 (delta 0), pack-reused 0
Checking out bed96c99236a81426c60b23bdd49e1dc59430de9
Traceback (most recent call last):
  File "py-git.py", line 49, in <module>
    main()
  File "py-git.py", line 47, in main
    dulwich.porcelain.push(repo, remote_repo, 'master')
  File "/home/yamazaki/test/venv/lib/python3.6/site-packages/dulwich-0.20.5-py3.6.egg/dulwich/porcelain.py", line 995, in push
    progress=errstream.write)
  File "/home/yamazaki/test/venv/lib/python3.6/site-packages/dulwich-0.20.5-py3.6.egg/dulwich/client.py", line 842, in send_pack
    new_refs = orig_new_refs = update_refs(dict(old_refs))
  File "/home/yamazaki/test/venv/lib/python3.6/site-packages/dulwich-0.20.5-py3.6.egg/dulwich/porcelain.py", line 984, in update_refs
    check_diverged(r, refs[rh], localsha)
  File "/home/yamazaki/test/venv/lib/python3.6/site-packages/dulwich-0.20.5-py3.6.egg/dulwich/porcelain.py", line 248, in check_diverged
    raise DivergedBranches(current_sha, new_sha)
dulwich.porcelain.DivergedBranches: b'bed96c99236a81426c60b23bdd49e1dc59430de9'
```

**Comment by jelmer** [comment]
On Mon, Jul 20, 2020 at 03:45:18PM -0700, Akihiro YAMAZAKI wrote:
> Same error occurred with master/HEAD.
> 
> ```
> Enumerating objects: 4, done.
> Counting objects: 100% (4/4), done.
> Compressing objects: 100% (4/4), done.
> Total 4 (delta 0), reused 3 (delta 0), pack-reused 0
> Checking out bed96c99236a81426c60b23bdd49e1dc59430de9
> Traceback (most recent call last):
>   File "py-git.py", line 49, in <module>
>     main()
>   File "py-git.py", line 47, in main
>     dulwich.porcelain.push(repo, remote_repo, 'master')
>   File "/home/yamazaki/test/venv/lib/python3.6/site-packages/dulwich-0.20.5-py3.6.egg/dulwich/porcelain.py", line 995, in push
>     progress=errstream.write)
>   File "/home/yamazaki/test/venv/lib/python3.6/site-packages/dulwich-0.20.5-py3.6.egg/dulwich/client.py", line 842, in send_pack
>     new_refs = orig_new_refs = update_refs(dict(old_refs))
>   File "/home/yamazaki/test/venv/lib/python3.6/site-packages/dulwich-0.20.5-py3.6.egg/dulwich/porcelain.py", line 984, in update_refs
>     check_diverged(r, refs[rh], localsha)
>   File "/home/yamazaki/test/venv/lib/python3.6/site-packages/dulwich-0.20.5-py3.6.egg/dulwich/porcelain.py", line 248, in check_diverged
>     raise DivergedBranches(current_sha, new_sha)
> dulwich.porcelain.DivergedBranches: b'bed96c99236a81426c60b23bdd49e1dc59430de9'

Ah, I see what's happening. This is a bug in the handling of shallow -
Repo.get_parents should check shallow commits.

Previously we didn't check graph ancestry so this particular code path
wasn't hit.

Jelmer

**Comment by zakkie** [comment]
It works! Thanks!
