### ISSUE TITLE
AttributeError in porcelain push on Dulwich 0.20.5

### ISSUE THREAD

**Issue by TheLastProject** [dulwich/dulwich#796]
Dulwich version: 0.25.0
OS: macOS Catalina (10.15.4 (19E287))

I'm not completely sure what went wrong, but the exception itself triggers in Dulwich:

```
Traceback (most recent call last):
  File "pext/ui/qt5.py", line 1360, in <lambda>
    lambda userinput, arg: callback(userinput, arg),
  File "/Users/sylviavanos/.config/pext/modules/pext_module_pass/__init__.py", line 248, in process_response
    self._edit_other_fields(name=" ".join(data[1:]), value=response)
  File "/Users/sylviavanos/.config/pext/modules/pext_module_pass/__init__.py", line 425, in _edit_other_fields
    self._save_password(name, data)
  File "/Users/sylviavanos/.config/pext/modules/pext_module_pass/__init__.py", line 312, in _save_password
    self._git_push()
  File "/Users/sylviavanos/.config/pext/modules/pext_module_pass/__init__.py", line 120, in _git_push
    porcelain.push(repo, remote_url, 'master', password=self.settings['ssh_password'])
  File "/usr/local/lib/python3.8/site-packages/dulwich/porcelain.py", line 996, in push
    (ref, error.encode(err_encoding)))
AttributeError: 'NoneType' object has no attribute 'encode'
```

The code that calls Dulwich is also available on GitHub. I've directly linked to the last call it does before Dulwich throws an exception:

https://github.com/Pext/pext_module_pass/blob/2b91e0d4ecdb2a27fca7d6c47d538632dcd45d7b/__init__.py#L120

I hope this helps. Please tell me if I can help debug anything!

**Comment by jelmer** [comment]
Thanks for the bug report. This should be fixed in master, and will be in 0.20.6. I'll see if I can do another release in the next couple of days.
