### ISSUE TITLE
Support for credential helpers

### ISSUE THREAD

**Issue by 0x2b3bfa0** [dulwich/dulwich#873]
### Follow-up to #768
> _it probably has a Git credentials helper that can provide the credentials - see https://www.git-scm.com/docs/gitcredentials_
>
> _dulwich does not support reading credentials from gitcredentials helpers, but that is not properly hooked up yet in the porcelain unfortunately. If you try this again in a couple of months it may work._ **https://github.com/dulwich/dulwich/issues/768#issuecomment-634385741**

It would be really nice to support credential loading from helpers like in the standalone `git` command‑line tool. Many users rely on HTTPS remotes and their system keychain for passwordless authentication, especially on macOS. 

### Minimal example

```python3
>>> from dulwich.porcelain import ls_remote
>>> ls_remote("https://github.com/user/repository")
```

#### Expected output

```console
{b'HEAD': b'···', b'refs/heads/main': b'···'}
```

#### Actual output

```console
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/···/site-packages/dulwich/porcelain.py", line 1618, in ls_remote
    return client.get_refs(host_path)
  File "/···/site-packages/dulwich/client.py", line 2089, in get_refs
    refs, _, _ = self._discover_references(b"git-upload-pack", url)
  File "/···/site-packages/dulwich/client.py", line 1906, in _discover_references
    resp, read = self._http_request(url, headers, allow_compression=True)
  File "/···/site-packages/dulwich/client.py", line 1875, in _http_request
    raise HTTPUnauthorized(resp.getheader("WWW-Authenticate"), url)
dulwich.client.HTTPUnauthorized: No valid credentials provided
```

### System configuration

```console
$ uname -a
Darwin ··· 19.6.0 Darwin Kernel Version 19.6.0: Tue Nov 10 00:10:30 PST 2020; root:xnu-6153.141.10~1/RELEASE_X86_64 x86_64
```
```console
$ python --version
Python 3.9.4
```
```console
$ pip show dulwich
Name: dulwich
Version: 0.20.23
Summary: Python Git Library
Home-page: https://www.dulwich.io/
Author: Jelmer Vernooij
Author-email: jelmer@jelmer.uk
License: Apachev2 or later or GPLv2
Location: /usr/local/lib/python3.9/site-packages
Requires: certifi, urllib3
Required-by: dvc
```
```console
$ cat /Applications/Xcode.app/Contents/Developer/usr/share/git-core/gitconfig
[credential]
        helper = osxkeychain
```

***

By the way: I love this project! ❤️

**Comment by jelmer** [comment]
This would be great to see implemented - it'd be great if somebody picked this up. I'm to help provide guidance and/or review pull requests.
