### ISSUE TITLE
clone() should be able to force ssl_verify=False

### ISSUE THREAD

**Issue by am21** [dulwich/dulwich#879]
should be able to do something like:
```
porcelain.clone(url, ssl_verify=False)
```
Unless there is an other way to do that?

**Comment by jelmer** [comment]
On Thu, Jun 03, 2021 at 03:06:40PM -0700, am21 wrote:
> should be able to do something like:
> ```
> porcelain.clone(url, ssl_verify=False)
> ```
> Unless there is an other way to do that?

You can pass in a custom configuration object (argument "config" for porcelain.clone) that sets http.sslVerify=false.

Cheers,

Jelmer

-- 
Jelmer Vernooĳ ***@***.***>
PGP Key: https://www.jelmer.uk/D729A457.asc

**Comment by am21** [comment]
```
from dulwich import porcelain
from dulwich.config import ConfigDict

config = ConfigDict()
config.set("http", "sslVerify", False)

porcelain.clone(url, "foo", config=config)
```
I get:
```
Traceback (most recent call last):
  File "dul.py", line 13, in <module>
    porcelain.clone(url, "foo", config=config)
  File "/local/mnt/workspace/amellan/src/dulwich/dulwich/porcelain.py", line 470, in clone
    fetch_result = fetch(
  File "/local/mnt/workspace/amellan/src/dulwich/dulwich/porcelain.py", line 1590, in fetch
    client, path = get_transport_and_path(
TypeError: get_transport_and_path() got multiple values for keyword argument 'config'

```

**Comment by jcobol** [comment]
@am21 : The dulwich code opens ~/.gitconfig for its configuration, so try setting a config option that way.
For an http-based clone:
```
git config --global http.sslverify false
```
or an SSH-based clone:
```
git config --global core.sshCommand 'ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no'
```
Or run the commands on another host that has Git installed and copy the ~/.gitconfig over.

**Comment by jcobol** [comment]
In the SSH case, I ended up having to do this before running a clone:
```
os.environ['GIT_SSH_COMMAND'] = "ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=false"
```
In my earlier test using `core.sshCommand`, I had an `~/.ssh/known_hosts` file left around so the test was invalid.  I don't know why core.sshCommand didn't work, but that's a Git/me problem. :)

**Comment by jelmer** [comment]
I've added support for the core.sshCommand setting in master.
